### ISSUE TITLE
TypeError: 'bool' object is not callable

### ISSUE THREAD

**Issue by spoon-today** [lingthio/Flask-User#100]
I have encountered this issue,

if current_user.is_authenticated() and user_manager.auto_login_at_login:
TypeError: 'bool' object is not callable

I modified to current_user.is_authenticated to solve problem immediately.
if there is any solution except modify that type error, help me plz.

**Comment by lingthio** [comment]
Hi @spoon-today ,
Does this happen in the Flask-User code base, or in your application code base?
Flask-Login v0.3 changed their API from a method (is_authenticated()) to a property (is_authenticated). Flask-User v0.6.8 should have addressed this issue.
See #92 .

**Comment by spoon-today** [comment]
Thank you :), and I'm sorry for my confusing. I had to check my dependency before posting issue.
I'm using older version of Flask-User (0.5.4).
Current version of Flask-User has no problem with this issue. :+1: 
Again, I'm so sorry.
