### ISSUE TITLE
User not allowed to login without email confirmation

### ISSUE THREAD

**Issue by terzano** [lingthio/Flask-User#102]
Hi, I have the following settings:

USER_ENABLE_USERNAME = False
USER_ENABLE_EMAIL = True
USER_ENABLE_CONFIRM_EMAIL = False
USER_ENABLE_LOGIN_WITHOUT_CONFIRM = True

However, I keep getting "Your email address has not yet been confirmed." and the user cannot login.
By the way, I am using the User/UserAuth DataModel

**Comment by terzano** [comment]
In the interim I added a default to the confirmed_at field in the User model so that it is confirmed automatically upon registration

 confirmed_at = db.Column(db.DateTime(), default=utcnow())

**Comment by b-ryan** [comment]
The documentation is wrong. The configuration parameter is actually called `USER_ENABLE_LOGIN_WITHOUT_CONFIRM_EMAIL`. See https://github.com/lingthio/Flask-User/blob/d4c6f4e3be47c9b39842874bd86416f16be250db/flask_user/settings.py#L29

**Comment by lingthio** [comment]
The documentation has been fixed a while ago.
