### ISSUE TITLE
Trouble with creating user manually and logging in

### ISSUE THREAD

**Issue by natejstar** [lingthio/Flask-User#109]
Hello,

I currently have a setup where the user table and user_auth table are separate. When I use the /user/register page and create a new user, everything works well and I can log in as that new user. What I am trying to do is create a new user and user_auth pair in my python code (i.e. without using the form to any extent so that new users can be generated on the fly).

For example, let's say I do the following:
Assuming I have a db.session object in my python code where I can add new objects and commit my work (both of which are fine for me)...

```python
new_user = user(username="testuser", email="test@test.com", first_name="testfirst", last_name="testlast")
db.session.add(new_user)
db.session.commit()
```

That block above works as expected and I have that new entry in my database. Let's say that the userid for new_user was generated by the database as 5. So now I need to create a user_auth entry to store the password for this user...

```python
pwd = random_password() # let's say it returned 'abc123'
hashed_pwd = app.user_manager.hash_password(pwd) # this call works fine for me
new_user_auth = user_auth(user_id=5, password=hashed_pwd)
```

At this point everything still seems great. I run a test, using the user_manager object in app, to check the following.. using the user object with id=5 created above, I can do app.user_manager.verify_password(user, 'abc123')
From that call I get True, so the hashing seemed to work fine when I made my user_auth entry in the database.

Then I run into trouble when I try to go to my normal login page on the browser and login with my newly created user with username 'testuser' and  password 'abc123'. Note that had I created the user through the register form, I would NOT run into the following problem. When I create the user as I showed above and hit login on the browser, it runs through my custom validate function in my custom LoginForm, that I call MyLoginForm (which subclasses the supplied flask-user LoginForm). I can tell it is using my custom version because of the logs I put in it. 

The part that surprises me is that when I log in with "testuser", 'abc123', it returns True (just like when I log in with users that were created through the register form), but instead of logging in and going to the profile page like my normal case, it just brings the log-in page up again, as if it didn't work. But the reason I know it's verifying username / pwd okay is the following block of code:

```python
# Handle successful authentication
if user and user_manager.verify_password(self.password.data, user):
    print "LOGIN6"
    return True                         # SUCCESSFUL authentication
```

I see the log "LOGIN6" every time so it seems like it is returning True and yet not logging in.

Is there something else in the login process that I am unaware of that would cause my manually created user ("testuser") to behave differently than a user created through the register form, when both are verifying username and password correctly?

Thank you!

**Comment by neurosnap** [comment]
Do you require email confirmation for users?  Was the user confirmed? `confirmed_at` in the `users` table.

**Comment by natejstar** [comment]
For now I have USER_ENABLE_CONFIRM_EMAIL set to false in my config file. I do have the confirmed_at in my table but I'm not using it yet.

**Comment by natejstar** [comment]
@neurosnap I found my issue - I didn't realize that the is_active flag must be True and otherwise the login does not work. Thanks!
