### ISSUE TITLE
@roles_required does not apply if placed before @app.route

### ISSUE THREAD

**Issue by Laogeodritt** [lingthio/Flask-User#137]
Version: 0.6.8, Python 3.5.2+ on Debian "testing" stream.

I've noticed that @roles_required will fail to check the role if it is placed outside of the @app.route decorator, as in:

```
@roles_required('administrator')
@app.route('/admin')
def admin_panel():
    # endpoint logic here
```

This is as specified in the docs here: https://pythonhosted.org/Flask-User/authorization.html#roles-required

This was tested by attempting to access the page as both a non-"administrator" non-anonymous user and an "administrator" user. I could access admin-only pages with both accounts.

The following works as expected:

```
@app.route('/admin')
@roles_required('administrator')
def admin_panel():
    # endpoint logic here
```

This works as expected (only the "administrator" user account can access this page; the other account results in an access error flash).

flask-login's @login_required works fine in either position.

**Comment by lingthio** [comment]
Hi @Laogeodritt , would you be willing to investigate this issue and suggest a solution?

**Comment by lingthio** [comment]
The Flask documentation states:

> When applying further decorators, always remember that the route() decorator is the outermost:

See http://flask.pocoo.org/docs/0.11/patterns/viewdecorators/

I will update the flask_user documentation.

Thanks!

**Comment by Laogeodritt** [comment]
Oh, good catch! I haven't implemented custom decorators in Flask so I hadn't read that doc page (though I can see how that makes sense in general). Interesting that @login_required seemed to work as the outermost—perhaps the Flask-User dev has a specific workaround in his decorator.

Documentation update sounds good.

**Comment by lingthio** [comment]
I've updated the examples in the docs.
