### ISSUE TITLE
Get the current user

### ISSUE THREAD

**Issue by subzeroDevelopment** [lingthio/Flask-User#139]
how can get the current user logged?

**Comment by LotosikRa** [comment]
`from flask_login import current user`

For more information read the source code.

**Comment by Laogeodritt** [comment]
@LotosikRa's correct but missed an underscore, that should read:

    from flask_login import current_user

Note that this also works (and is equivalent, because flask_user imports it from flask_login itself):

    from flask_user import current_user

**Comment by subzeroDevelopment** [comment]
Thank's for help me
