### ISSUE TITLE
ImportError: cannot import name make_secure_token

### ISSUE THREAD

**Issue by semal** [lingthio/Flask-User#143]
from flask_login import LoginManager, UserMixin as LoginUserMixin, make_secure_token

when running this line, error catch for python 2.7

**Comment by dtamez** [comment]
Same here.

**Comment by bjones1** [comment]
That also worked for me (Python 3.5). Thanks, @dtamez!

**Comment by lingthio** [comment]
Scheduled to be fixed in upcoming v0.6.9.

**Comment by bjones1** [comment]
Great! Thanks for a great Flask extension. I really appreciate the work you've put into this.

**Comment by lingthio** [comment]
Released in v0.6.9.
