### ISSUE TITLE
Include Spanish in the languages shiped by default in Flask-User

### ISSUE THREAD

**Issue by JavierLopezMunoz** [lingthio/Flask-User#157]
Hello,

Actually I already have the po file for Spanish because I did it for one personal project. I am more than happy to contribute with the translation to Spanish.

If it is ok for you, just tell what shall I do next.

Thanks

**Comment by lingthio** [comment]
See #152 . This will be available in the next 0.6.10 release.

**Comment by JavierLopezMunoz** [comment]
Great, thanks for the very fast answer.
