### ISSUE TITLE
my contrib for MongoDB and Flask_User

### ISSUE THREAD

**Issue by yattamax** [lingthio/Flask-User#166]
Hi, maybe you have refused this feature in the past or you are working on this request, but for a my personal project I have made some modify to Flask_User 0.6 and I have made a DBAdapter for support MongoDB (with MongoAlchemy) as backend and now this work.

This feature can ben interesting for the project ? 
If you are interested can be send my code :)

Best Regards
Massimiliano :)

**Comment by lingthio** [comment]
Hi @yattamax,
Yes, I'm interested. You can email me the dbadapter or you can submit a pull request.
Thanks,
Ling

**Comment by lingthio** [comment]
See #37
