### ISSUE TITLE
Form doesn't translate

### ISSUE THREAD

**Issue by zxygentoo** [lingthio/Flask-User#171]
hi

I've followed doc setup babel and it seems working, all trans strings in templates  got translated correctly, changing po and recompile also shown right changes.

But, all forms do not translate (labels, err msgs etc.). 

Searching issues doesn't yield useful result. Any ideas? Thanks!

**Comment by lingthio** [comment]
Hi @zxygentoo,
Please specify a specific form and string that does NOT get translated, and I can look into your issue. Thanks.
