### ISSUE TITLE
Lack of compatibility with wtforms 3.0 - may be a slight oversight

### ISSUE THREAD

**Issue by fjmalass** [lingthio/Flask-User#176]
When using reforms 3.0, wtf.validators.Required is not longer used.
Propose to change InviteForm  in forms.py to 
have 
validators.Required(_('Email is required')) 
replaced by 
validators.DataRequired(_('Email is required')),

**Comment by lingthio** [comment]
Thanks for the bug report. I have updated the code.
Not sure when I will build the next release.

**Comment by fjmalass** [comment]
I really like Flask-User If you need any help on that front, I am more than
happy to give you hand.

Francois

Francois J. Malassenet

**Comment by lingthio** [comment]
Fixed in v0.6.19.
