### ISSUE TITLE
Unable to pip install version 0.6.11

### ISSUE THREAD

**Issue by gprasanth** [lingthio/Flask-User#180]
> Could not find a version that satisfies the requirement Flask-User==0.6.11 (from -r requirements.txt (line 14)) (from versions: 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 0.6, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.6.8, 0.6.9, 0.6.10, 0.6.12)
> No matching distribution found for Flask-User==0.6.11 (from -r requirements.txt (line 14))
> 

Any reason why this specific version is missing?

**Comment by ruaridht** [comment]
I have found that the revision history shows `0.6.11` to have been skipped:
https://github.com/lingthio/Flask-User/blob/v0.6/docs/source/index.rst

The commit in question is:
bc004f417b4559b7cf10090b653553eb4863495e

I have just upgraded to 0.6.12. My questions are: Is this an error somehow? If not, I don't think versions should be skipped like this.

**Comment by StephenOrJames** [comment]
I find this a bit strange, because I have installed 0.6.11 via `pip` with no issue on two different operating systems (Ubuntu and Windows) in the past, which suggested that the version did in fact exist at some point.

**Comment by lingthio** [comment]
My apologies all. PyPi changed its services in July, and I've been struggling getting up to speed with the new environment. Hence the many 0.6.11 - 0.6.19 versions. 0.6.19 should have fixed many install issues.
