### ISSUE TITLE
Installation Fails Because of __version__ Import (v0.6)

### ISSUE THREAD

**Issue by StephenOrJames** [lingthio/Flask-User#183]
c88b376 tried to make things easier to manage by doing `from flask_user import __version__ as flask_user_version` in `setup.py`. However, that has an undesirable consequence: users who don't already have `passlib` installed could face an `ImportError`, preventing installation of Flask-User.

To reproduce (ensure `passlib` is not already installed):
```
$ pip install --no-cache-dir Flask-User==0.6.17
Collecting Flask-User==0.6.17 (from -r requirements.txt (line 13))
  Downloading Flask-User-0.6.17.tar.gz (62kB)
    100% |████████████████████████████████| 71kB 6.0MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-c6f9o6kh/Flask-User/setup.py", line 5, in <module>
        from flask_user import __version__ as flask_user_version
      File "/tmp/pip-build-c6f9o6kh/Flask-User/flask_user/__init__.py", line 7, in <module>
        from passlib.context import CryptContext
    ImportError: No module named 'passlib'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-c6f9o6kh/Flask-User/
```
Note that if the packages are cached, it could also appear to work fine, which is why `--no-cache-dir` is needed.

**Comment by lingthio** [comment]
Hi @StephenOrJames,
Yes, I made a mistake some 0.6 packages. It has been fixed in 0.6.19.

**Comment by matthijskooijman** [comment]
Hm, I can't quite find this 0.6.19 release anywhere? It seems that git tags haven't been created since the 0.5 series, but I can't find a commit fixing this in (or releasing 0.6.19) in either the master or 0.6.x branches? And [pypy](https://pypi.python.org/pypi/Flask-User) still seems to list 0.6.17 as the latest version. I might be ignorant on how this works and I might just need to be more patient, but it seems I'm missing something here?

**Comment by lingthio** [comment]
I'm so sorry. I apparently was overwhelmed, and forgot to build release v0.6.19. I've fixed this. It's now available on PyPi. So sorry!

**Comment by matthijskooijman** [comment]
No problem. Thanks!

**Comment by anygizer** [comment]
So the code [here in the v0.6 branch](https://github.com/lingthio/Flask-User/blob/v0.6/setup.py) reflects the v0.6.19 code released on PyPi, except the \_\_version\_\_ change in [setup.py](https://github.com/lingthio/Flask-User/blob/60c4e391a715e9c43b321a37fc2b078f99b97760/setup.py#L5) and [flask_user/__init__.py](https://github.com/lingthio/Flask-User/blob/60c4e391a715e9c43b321a37fc2b078f99b97760/flask_user/__init__.py#L31)?

**Comment by lingthio** [comment]
@anygizer : My bad, I forgot to push my local repository.
The v0.6 branch now reflects the v0.6.19 code on PyPi.
Ling.
