### ISSUE TITLE
Regression on 0.6.14 version: pip3 install fails

### ISSUE THREAD

**Issue by NinjaKitou** [lingthio/Flask-User#185]
Hello,

I think there is a regression in the setup.py file, introduced in the 0.6.14 release.
From this release, the setup.py is importing the flask_user module, invoking the \_\_init\_\_.py.

The problem lies when starting with a fresh installation, typically when building a docker image,
and using pip to install the packages.

it fails with the following error:
>
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-z9z019ri/flask-user/setup.py", line 5, in <module>
        from flask_user import __version__ as flask_user_version
      File "/tmp/pip-build-z9z019ri/flask-user/flask_user/__init__.py", line 7, in <module>
        from passlib.context import CryptContext
    ImportError: No module named 'passlib'

Indeed, at this time in the build, the __passlib is not yet installed__.
Even when trying to install the passlib, it fails with all the dependencies the module have (second one being flask).

Am I doing something wrong ?

**Comment by lingthio** [comment]
Hi @NinjaKitou . The v0.6.19 release has addressed this problem. Ling

**Comment by NinjaKitou** [comment]
Ah yes sorry about that, didn't see the #183, thanks a lot!

**Comment by Bhavatu** [comment]
Where can this v0.6.19 be found?

**Comment by lingthio** [comment]
Oops. My bad. I meant to write 0.6.17. I fixed the previous comment.
Ling

**Comment by lingthio** [comment]
OMG. I must have been in an overwhelmed place. I did mean v0.6.19. I just hadn't built nor released it. I just checked, and v0.6.19 is up and running on PyPi.
