### ISSUE TITLE
Username Enumeration on Login Page

### ISSUE THREAD

**Issue by dbohannon** [lingthio/Flask-User#189]
The default Login page provided by Flask-User at /users/sign-in is vulnerable to username enumeration. When submitting an invalid username, the "Username does not exist" message is rendered in the response.

**Comment by lingthio** [comment]
Hi @dbohannon ,
This is a feature that can be disabled with USER_SHOW_USERNAME_EMAIL_DOES_NOT_EXIST=False.
The default is True for backward compatibility. We plan to change the default to False in the upcoming v0.9.

**Comment by lingthio** [comment]
Available in v0.6 and v1.0 with a safe default for v1.0
