### ISSUE TITLE
Deprecated import for flask_babel

### ISSUE THREAD

**Issue by rbrook** [lingthio/Flask-User#196]
In file `flask_user/translations.py` there is an import (L46):
`from flask.ext import babel`
which is used the next line:
`return ctx.flask_user_translations.merge(babel.get_translations())`

This is deprecated and Flask-Babel throws a warning.

> python3.5/site-packages/flask_user/translations.py:46: ExtDeprecationWarning: Importing flask.ext.babel is deprecated, use flask_babel instead.
    from flask.ext import babel

Instead it should be something like:
`from flask_babel import get_translations as fbabel_get_translations`
and the next line should be:
`return ctx.flask_user_translations.merge(fbabel_get_translations())`

**Comment by yuhr123** [comment]
/Users/Herald/Code/flask/lib/python3.6/site-packages/flask_user/translations.py:46: ExtDeprecationWarning: Importing flask.ext.babel is deprecated, use flask_babel instead.
  from flask.ext import babel

**Comment by lingthio** [comment]
This has been fixed a while ago. Closing it.
