### ISSUE TITLE
Password reset signal isn't sent

### ISSUE THREAD

**Issue by bbc2** [lingthio/Flask-User#202]
The documentation (https://flask-user.readthedocs.io/en/v0.6/signals.html) says a `user_reset_password` is sent went the user resets its password, but that's not the case.  That's what I observed and also confirmed by reading the code.

This affects both v0.6 and v0.9 it seems.

**Comment by bbc2** [comment]
It's nice to see that the fix has been applied to both the v0.6 and v1.0 branches.  Could you release a new v0.6.x version with that fix?  That would be useful while v1.0 is still in alpha.

**Comment by lingthio** [comment]
The v0.6 code base seems to send the user_reset_password signal.
See https://github.com/lingthio/Flask-User/blob/v0.6/flask_user/views.py#L608
Are you experiencing it differently?
