### ISSUE TITLE
URL redirect 404 issue after login

### ISSUE THREAD

**Issue by northtree** [lingthio/Flask-User#204]
I have 404 URL Not Found issue on missing the question mark (?) for redirect URL.

127.0.0.1 - - [29/Mar/2018 16:50:41] "GET /map?map=here&ol=cluster HTTP/1.1" 302 -
127.0.0.1 - - [29/Mar/2018 16:50:41] "GET /user/sign-in?next=/mapmap%3Dhere%26ol%3Dcluster HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 17:07:17] "POST /user/sign-in?next=/mapmap%3Dhere%26ol%3Dcluster HTTP/1.1" 200 -
127.0.0.1 - - [29/Mar/2018 17:07:19] "POST /user/sign-in?next=/mapmap%3Dhere%26ol%3Dcluster HTTP/1.1" 302 -
127.0.0.1 - - [29/Mar/2018 17:07:19] "GET /mapmap=here&ol=cluster HTTP/1.1" 404 -

BTW, I am using Flask-User 0.6.19 (Python 2.7).  

How could I fix this issue? Thanks.

**Comment by lingthio** [comment]
What version of Flask-User are you using?
A fix in make_safe_url() was fixed in Flask-User v0.6.20.

**Comment by northtree** [comment]
@lingthio Thanks for your help. My previous version is 0.6.19. Just upgrade to 0.6.20 and fix this issue.
