### ISSUE TITLE
use setup_tools extras_require to clean up forced unnecessary dependencies

### ISSUE THREAD

**Issue by pjz** [lingthio/Flask-User#207]
Right now a good amount of the Installation docs are about what you may need to install or uninstall.
It would be better to wrap that up some, I think.  Maybe define a set of extras like:

'defaults': ['bcrypt', 'Flask-SQLAlchemy', 'Flask-Mail']

which lets users emulate an old 'default' install before by doing 'pip install Flask-User[defaults]', while not forcing those pieces to be installed and then uninstalled by others, who might prefer to have their project depend on 'Flask-User, PynamoDB, MyCustomSTMPEmailAdapter' or something.

**Comment by lingthio** [comment]
Hi @pjz ,
I don't plan on implementing your suggestion. I'm guessing that 90+% of users will want to use bcrypt/sqlalchemy/flask-mail. I prefer that the 10% take extra steps rather than asking 90% to install flask-user using (a lesser known pip feature)`` pip install Flask-User[defaults]``.
