### ISSUE TITLE
self.UserInvitationClass not set in UserManager() and is checked during intialization

### ISSUE THREAD

**Issue by h-vishal** [lingthio/Flask-User#223]
If a UserInvitationClass is passed in while initializing UserManager, the class member UserInvitationClass is not set which raises a ConfigError. To fix this the UserInvitationClass member should be set when the argument UserInvitationClass is passed in.

**Comment by h-vishal** [comment]
@Sb1190 you are trying to access the 'UserInvitationClass' member which you should not need to do, StackOverflow is probably a more appropriate forum for you question.

**Comment by vvch** [comment]
Seems like this attribute was commented out [here](https://github.com/lingthio/Flask-User/commit/8e89a5b6f6f5604c52191f4fdbbacc58ef8e2537?diff=split#diff-45297e1e6e768c6b6f9de2c56f83cfcaR80) about a year ago, but is still checked [here](https://github.com/lingthio/Flask-User/blob/8e89a5b6f6f5604c52191f4fdbbacc58ef8e2537/flask_user/user_manager.py#L268) causing exception (but only if USER_ENABLE_INVITE_USER is set)

**Comment by nerdnum** [comment]
Hi

Running Flask-User 1.0.1.5 on Windows10 with Python 3.7.2 and it is running perfectly.

In my hosting environment Ubuntu 19.04, Python 3.7.3 using the same version of Flask-User, I get the error below. Any idea?

` File "run.py", line 3, in <module>
    app = create_app()
  File "/home/lbecker/maranatha/app/__init__.py", line 89, in create_app
    user_manager = UserManager(app, db, User, UserInvitationClass=UserInvitation)
  File "/home/lbecker/maranatha/venv/lib/python3.7/site-packages/flask_user/user_manager.py", line 56, in __init__
    self.init_app(app, db, UserClass, **kwargs)
  File "/home/lbecker/maranatha/venv/lib/python3.7/site-packages/flask_user/user_manager.py", line 203, in init_app
    self._check_settings(app)
  File "/home/lbecker/maranatha/venv/lib/python3.7/site-packages/flask_user/user_manager.py", line 289, in _check_settings
    if self.USER_ENABLE_INVITE_USER and not self.UserInvitationClass:
AttributeError: 'UserManager' object has no attribute 'UserInvitationClass'
`

**Comment by GitMorin** [comment]
I can confirm that what @nerdnum said solves the issue
