### ISSUE TITLE
Add support for Python 3.7 and 3.8, drop 2.6, 3.3 and 3.4

### ISSUE THREAD

**Issue by and-semakin** [lingthio/Flask-User#281]

**Comment by lingthio** [comment]
I agree that we can drop support for python 2.6 in Flask-User 1.0. Is there a reason why we are considering dropping Python 3.3 and 3.4?

**Comment by and-semakin** [comment]
Of course, I've just created this issue to not loose the idea :)

**Comment by and-semakin** [comment]
We had conversation with @lingthio about supported versions on email, I just want to put here my points:
* Flask, our upstream project, currently supports only 2.7 and 3.5+;
* Flask-User, according to [PyPI stats](https://pypistats.org/packages/flask-user), has approximately 0 downloads in last 120 days from Python 2.6 and 3.3 and a very few downloads from 3.4;
* each old version of Python restricts us from what language features we can use; for example, if we support Python 2.6 then we can't use set and dict comprehensions and [many other useful little things](https://docs.python.org/2/whatsnew/2.7.html).

So I would like to drop support for at least Python 2.6 and 3.3 as soon as possible. Probably we can also drop support for Python 3.4 as it is also recently reached its EOL.

**Comment by lingthio** [comment]
I think Python version support is a balance between development effort, and the user's desire to not be forced to upgrade their Python version just for the sake of using Flask-User. According to our download statistics, there are 1-3% users marked as "null" (unknown or not tracked).

So my question is: If we continue to support Python 2.7, how much extra development effort is needed to continue to support Python 2.6? Unless we have a valid use of 2.7 features (dict /set comprehensions, OrderedDicts, etc.), I don't see us efforting much to support 2.6. Am I missing something here?

And if we continue to support Python 3.5, how much development effort is there for us to continue supporting Python 3.3?  I don't see us efforting much to support 3.3. Am I missing something here?

Thank for your collaboration, @and-semakin !

**Comment by and-semakin** [comment]
I'm completely happy with this outcome! Thank you @lingthio!

**Comment by and-semakin** [comment]
Python 3.7 and 3.8 support added, Python 2.6 and 3.3 are dropped.
