### ISSUE TITLE
Site is showing last logged in user

### ISSUE THREAD

**Issue by charlbury** [lingthio/Flask-User#284]
I have an issue where my site is now showing the last logged in user. If I go to an incognito tab and then load the site, it shows a user already logged in.

I'm sure I must have it set up wrong but I'm struggling to even think of how to debug the issue. Can you suggest what I should look at to sort it out, or how I should debug it?

The site and the user login and authentication has been working for many weeks, so, a recent change must have triggered this issue but having trawled through the last weeks worth of changes I cannot identify anything.

What would cause it to show the last logged in user that must be from another browser session?

Thanks

**Comment by charlbury** [comment]
So, I reverted my code back 5 versions and re-released each version of code again, testing for this error each time. I was never able to get the problem to manifest itself again. I released the final version of the code, which in theory was setting the site back to exactly the same acode and settings as it was when I saw users already logged in.

**Comment by and-semakin** [comment]
Hi @charlbury! Sounds crazy. Feel free to reopen this issue if the problem appears again.
