### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by joeybellerose** [lingthio/Flask-User#287]
I was unable to install the package with 'pip install Flask-User' and got this error. 

pip install Flask-User
Collecting Flask-User
  Using cached https://files.pythonhosted.org/packages/10/3c/00776d0521f6269e6df65e3e0a80bfd11fff7d9d87a514a439db3c85b2bd/Flask-User-1.0.2.2.tar.gz
    ERROR: Command errored out with exit status 1:

After installing flask-login, I was able to install flask-user.  My apologies if this is an oversight on my end, but I haven't worked with flask-user yet and was just following the docs

**Comment by and-semakin** [comment]
Hi @joeybellerose! Thank you for taking a minute and writing us! But I'm afraid that we don't have enough data to diagnose this issue.

Questions:
* What Python version do you use? You can check it if you execute `python -V`.
* What pip version do you use? `pip -V`
* Have you tried to just re-run the command? Probably it was some one-time network related issue.

Just checked it, I can successfully install Flask-User on Python 3.6, 3.7 and 3.8 using pip 19.3.1.

**Comment by and-semakin** [comment]
I'm going to close the issue, but if the error appears again -- feel free to write here :)

**Comment by joeybellerose** [comment]
@and-semakin , my apologies for not giving you more info.  

pip version: 19.3.1
python verison: 3.8
I re-ran the command a couple of times and was unable to get it to work until I installed Flask-Login.  

Either way, agreed that there is no action here....just wanted to let you know in case it pops up for someone else.
