### ISSUE TITLE
Is there a way to specify single user only by blocking other register attempts?

### ISSUE THREAD

**Issue by hakanu** [lingthio/Flask-User#295]
Thanks for the great project, really easy to use. I'm wondering if there is a way to just let first user register and then block that page fully and only let login go through.

**Comment by Chaostheorie** [comment]
Maybe you can alter the registering form with a check that turns False after the first registration.

**Comment by hakanu** [comment]
i've added a custom user manager.
https://github.com/hakanu/pervane/blob/master/pervane/serve.py#L175

Closing this.
