### ISSUE TITLE
Python 3.8 : ImportError: cannot import name 'clock' from 'time'

### ISSUE THREAD

**Issue by UrbanJakubDev** [lingthio/Flask-User#312]
In Python 3.8 `clock` is depricated and doesn't exist in python 3.8.

![image](https://user-images.githubusercontent.com/27211973/83753693-0abb9b00-a66b-11ea-9c2e-55f90eae9e01.png)

![image](https://user-images.githubusercontent.com/27211973/83753712-11e2a900-a66b-11ea-8edb-b65cec38a51f.png)

Working with `from time import perf_counter as timer`

**Comment by Chaostheorie** [comment]
This isn't caused by Flask User but instead by passlib (See traceback file). You may consider upgrading passlib in your venv. If the issue consists open an issue [Here](https://foss.heptapod.net/python-libs/passlib/issues)
