### ISSUE TITLE
User Invitation Functionality

### ISSUE THREAD

**Issue by neurosnap** [lingthio/Flask-User#47]
I'm looking to send an invite via email to a user, sort of like an admin tool to add users without them "registering" through the normal process.

I see in the `USER_REQUIRE_INVITATION` config variable with the comment "not yet implemented."  I'm wondering if you are in the process of fleshing out this functionality or is it more of a wish list?

As it stands right now I'm attempting to manually go in and generate this process.  My plan is to utilize the password reset (`user_manager.generate_token()`, `reset_password_link`, `User.reset_password_token`, etc.) functionality that has already been created but send it to a custom view, email template, etc.

Would you suggest this as the best course of action?  The reason why I'm asking is if there is a plan to incorporate "user invitation" functionality, I would be more than willing to fork Flask-User and attempt to contribute.

Awesome package btw, the customizability and readability of the package has been really great.

**Comment by lingthio** [comment]
Thanks to @neurosnap , this feature has been added in Dec 2014.

**Comment by lingthio** [comment]
This feature has been released in v0.6.1.

**Comment by tOlorun** [comment]
Great work guys,

iam just discovering flask-user today and i have already gone through the documentation.

my question is this . .. how do i actually use the flask-user invitation function

Many thanks for your prompt response

Cheers

**Comment by lingthio** [comment]
It's been a while ago, but there's a file in the example_apps dir that should point you towards the right direction: https://github.com/lingthio/Flask-User/blob/v0.6/example_apps/invite_app.py

**Comment by tOlorun** [comment]
Thanks @lingthio will try it out and get back to you

many thank

**Comment by mgd722** [comment]
Did `USER_REGISTER_REQUIRES_MODERATION` make it into any release yet?  I searched for it and it doesn't seem so, but I wanted to make sure it's not included under a different name or something.
