### ISSUE TITLE
Python 3.4 Signals

### ISSUE THREAD

**Issue by neurosnap** [lingthio/Flask-User#58]
Flask v0.10.1
Flask-User v0.6.1

The following signal does not trigger in python 3.4, but works in python 2.7:

    from flask.ext.user.signals import user_logged_in

    @user_logged_in.connect_via(app)
    def track_login(sender, user, **extra):
        sender.logger.info('user logged in')

If I change the way the signal is imported, it works fine in python 3.4 AND python 2.7:

    from flask.ext.user import signals

    @signals.user_logged_in.connect_via(app)
    def track_login(sender, user, **extra):
        sender.logger.info('user logged in')

I'm starting to wonder if this is an issue with Flask and how it imports extensions into flask.ext, very strange behavior nonetheless ... I'll continue to investigate.

**Comment by neurosnap** [comment]
Replicating the error: https://github.com/neurosnap/Flask-User/blob/signals/example_apps/signals_app.py

**Comment by lingthio** [comment]
Available in v0.6.3.
