### ISSUE TITLE
Confused about 1.0.0

### ISSUE THREAD

**Issue by jdjoode** [lingthio/Flask-User#69]
I am getting confused here. In the docs I read that 0.6.* would be incompatible with later releases. But is 0.6.* not the latest release, then? Where can I get the 1.0.0 release?

**Comment by neurosnap** [comment]
0.6.1 is the latest version.  I think the comment you are referencing is: "We’re starting to work on Flask-User 1.0 which will break backwards compatibility with v0.5 and v0.6." is merely a warning about some of the changes @lingthio is proposing for 1.0

**Comment by jdjoode** [comment]
Ah ok that makes sense. I think it is probaby better for new users to delete that comment... does not add anything apart from the doubt that this package will not be supported for a long time anymore.

Thanks for your reply.
