### ISSUE TITLE
Login redirects to the /home URL, causes confusion

### ISSUE THREAD

**Issue by bobwaycott** [lingthio/Flask-User#71]
EDIT: Changing issue description, since I can't just delete the whole thing.

I just ran into a rather frustrating issue (that is mostly my fault).

Here's the scenario:

- app is in `debug` mode
- had dummy `User` instances already loaded in the db from other dev work
    - not using `UserMixin` because I haven't in prior projects and don't really like all that extra code
- wired up flask-user as i've done before in other projects
- use forgot-password to receive email & set password on one of the fake users
- totally forget that there's an `active` flag on the `User`
- stay in endless loop that looks like login is not working & constantly redirecting to itself, **but to the new /home URL**, leading someone who has used flask-user in the past to wonder where the heck that came from (and then discover it's hard-coded in the pkg).

I just wasted hours trying to figure out where in the heck this `/home` URL came from, what view it was tied to, and why my once-working Flask-User process was suddenly broken in the latest version. And it was all because I hadn't set any `active` flags to `True`. Oh, and once I figured that out, now I **have** to have a `has_confirmed_email` attr/method on my `User` object.

*Sigh.*

**Suggestion:** if the app is in `debug` mode, it'd be pretty awesome to have some more errors thrown, console messages logged out, or *something* that helps identify why things are not working in places they *should*, but something that is expected is either not present, or not what it should be. i know there are some calls to set flash messages, but that's not enough in all scenarios--especially if we're customizing templates and don't have flash messages included. 

Maybe it's just me, but Flask-User is *increasing* the amount of schema & model attributes it needs just to successfully pull off **authentication**. This is starting to feel like very poor design spiraling out of control. I'm not sure I am going to want to keep using Flask-User if this is how the project is going to be going in the future. I've now done two upgrades, and both times have found me wasting hours trying to discover unintuitive behavior based on schema/model assumptions.

**Above all else**, if the app is in `debug`, that should be the time to throw all kinds of show-stopping messages at a developer that they don't have things right. Or maybe allow it to be activated with a flag or something. But when you're using a 3rd-party lib that you're trying to treat like a black box, when the box doesn't work and doesn't tell you, things get pretty annoying rather quickly.

**Comment by neurosnap** [comment]
Greetings, I agree, the package is getting big.  If you are simply interested in a simple user authentication protocol, I'd suggest Flask-Login (https://flask-login.readthedocs.org/en/latest/), which is what this module is dependent upon.

Flask-User attempts to do a lot more than a simple login while trying to not sacrifice customizability.  When using this package I find myself diving into the source more so than other projects, but that is in large part because of how customizable it is and because deploying a fully-featured user authentication system necessitates scrutinizing every nuance of the system.

When referencing your specific issue, there is a flash that should have been sent to the login template upon failing user authentication:
https://github.com/lingthio/Flask-User/blob/master/flask_user/views.py#L704

Do you have `flash` set up in your application?

**Comment by bobwaycott** [comment]
@neurosnap thanks for the reply, mate.

I do have `flash` setup, and included in my templates, but for some reason, the message about `active` status wasn't showing up at all. I just kept being redirected from `/login` to `/home`.

Moreover, I do want some of Flask-User's heightened user creation/auth features -- things like confirmation emails, password tokens/resets, etc. So, I don't want simple user auth, else I would have just gone with Flask-Login or rolled a simple login method myself. It's all the confirm/reset/forgot/email features that I find helpful -- *but only insofar as they are related to handling going from creating > authenticating a `User`. After auth, my projects are generally really large, complex, custom applications my clients use to manage their business processes. Things like profiles are either not necessary, or implemented in custom ways.

I just don't think all the extra profile stuff should be hard-coded into the app. Seems things ought to be broken up into some smaller disabled-by-default features that developers can turn on.

I also think that, at least when in `debug`, it might be worth having some verbose logging going to the console or something. Only having it routed through the `flash` system, expecting it to show up in templates can leave things in a state where devs like me, who don't allow blanket flash messages to appear everywhere in client applications, can't figure out what is happening.

Anyway, I'd have deleted this issue if I could. Feel free to close it, as it seems to be less of a bug, and more of an issue with documentation not really being clear (imo) about all that is **mandatory** to get things working correctly. When I read in the docs that one should include the `UserMixin`, I see it as a suggestion, like Flask-Login's `UserMixin` (on which Flask-User's is based). I don't anticipate it being something that will prevent me from getting user's logged in at all.

I really think all this `User` + `UserAuth` + `UserProfile` + `UserRoles` + `UserEmails` schema/model dependence is *really* getting out-of-hand. And the docs just aren't making it clear enough just how much Flask-User is depending on all these things in various ways.

**Comment by bobwaycott** [comment]
Maybe the project should be renamed to "Flask-User (and the kitchen sink)" :)

**Comment by nZac** [comment]
I ran into this today as well and tripped me up, luckily I didn't get to far down the rabbit hole.  My problem specifically was this redirect https://github.com/lingthio/Flask-User/blob/master/flask_user/views.py#L705 

I wonder if we could customize that route in anyway? Maybe a new route for a user who is inactive? I would much prefer that they are sent to the sign in page again with the same flash message. 

I can put together a PR if that is something you would be interested in.  We might also consider the same for https://github.com/lingthio/Flask-User/blob/master/flask_user/views.py#L714. To my knowledge that is the only two place `user.home` is used.

**Comment by lingthio** [comment]
Hi all, Thanks for taking the time to weigh in.
Re: /home URL: See issue #70.
Re: User + UserAuth + UserProfile + UserRoles + UserEmails schema: See issue #70. ;-)
Closing this as a duplicate issue.

**Comment by lingthio** [comment]
Fixed in v0.6.3.
