### ISSUE TITLE
documentation page for starter app is outdated

### ISSUE THREAD

**Issue by silpol** [lingthio/Flask-User#77]
the page is https://pythonhosted.org/Flask-User/flask_user_starter_app.html

it cites:

Files of interest:
    app/startup/init_app.py
    app/users/models.py
    app/templates/flask_user/*.html
    app/templates/user/user_profile_page.html

however I do not see app/users/* hierarchy at all after fetch from git

**Comment by lingthio** [comment]
@silpol : Thank you for taking the time to report this. I've corrected the docs to reflect the recent directory reorganization and it now reads:

Files of interest:
app/startup/init_app.py
app/models/user.py
app/templates/flask_user/*.html
app/templates/users/user_profile_page.html
