### ISSUE TITLE
Question: How to detect unsuccessful logins.

### ISSUE THREAD

**Issue by scalloty** [lingthio/Flask-User#80]
How to detected unsuccessful login? 
I want to show captcha after several unsuccessful attempts to login.

**Comment by lingthio** [comment]
There is currently no elegant way to do this but it's possible by defining your own login view function:

* Cut and past this: https://github.com/lingthio/Flask-User/blob/master/flask_user/views.py#L209-L258
and rename login() to my_login()
* Change `UserManager(db_adapter, app)` to `UserManager(db_adapter, app, login_view_function=my_login)`
* Near the bottom of my_login: 

```
        if user:
            # Log user in
            return _do_login_user(user, login_form.next.data, login_form.remember_me.data)
        else:
            # count your failed login attempts here.
```

**Comment by neurosnap** [comment]
I think it all depends on how what you want to consider an unsuccessful login attempt and how long one should continue to keep track of those attempts.  I think most of this could actually be done in javascript through browser storage mechanisms: https://developer.mozilla.org/en-US/docs/Web/API/Storage

Ofc you could also try http://pythonhosted.org/Flask-Session/
