### ISSUE TITLE
Switching away from py-bcrypt backend

### ISSUE THREAD

**Issue by Shizmob** [lingthio/Flask-User#82]
As passlib duly notes, all pip versions (and HEAD too) of `py-bcrypt` are vulnerable to the [BSD wraparound bug](http://www.openwall.com/lists/oss-security/2012/01/02/4):

`UserWarning: passlib.hash.bcrypt: Your installation of the 'pybcrypt' backend is vulnerable to the bsd wraparound bug, and should be upgraded or replaced with another backend (this warning will be fatal under passlib 1.7)`

Aside from being a serious security vulnerability, being fatal in passlib 1.7+ means it will also make Flask-User unusable under that version until fixed.

Alternative backends supported by passlib like [bcrypt](https://pypi.python.org/pypi/bcrypt/2.0.0) should be considered switching to.

**Comment by Xender** [comment]
Passlib changelog for 1.6.4 mentions that [it will detect vulnerable versions and "automatically enable a workaround"](https://pythonhosted.org/passlib/history.html#bcrypt-changes).
Also, this changelog doesn't mention this warning becoming fatal in 1.7.

And it's not that `py-bcrypt` is going to be unpatched forever?

Anyway, the same changelog mentions that `bcrypt` will now become preferable implementation.
Switching the backend for passlib should be just matter of installing `bcrypt` and removing `py-bcrypt`, right?
Will simple find-and-replace of module name in this repo cut it then?

**Comment by Shizmob** [comment]
The documentation may not say it, the source code does however: https://bitbucket.org/ecollins/passlib/src/fa26802fc88fbc6b2d4b9676970bed7e6d53fc9d/passlib/handlers/bcrypt.py?at=default#bcrypt.py-314 (which also explains the `UserWarning`, since that is what `warnings.warn` emits by default.

>And it's not that py-bcrypt is going to stay unpatched forever?

`py-bcrypt` seems unmaintained, with no release in over two years and not having moved off Google Code yet.

>Anyway, the same changelog mentions that `bcrypt` will now become preferable implementation.
>Switching the backend for passlib should be just matter of installing `bcrypt` and removing `py-bcrypt`, right?
> Will simple find-and-replace of module name in this repo cut it then?

Yep. `py-bcrypt` is not anywhere used directly by `Flask-User`, just added to the `requirements.txt` files and `setup.py`. As `passlib` automatically picks up on backends, changing these files to use `bcrypt` should do the trick indeed.

**Comment by lingthio** [comment]
Thank you all for contributing. It turns out that you need one of the latest versions of passlib in addition to bcrypt to make it work in Python 3.3 and 3.4. This combo seems to work for me:

    passlib==1.6.5
    bcrypt==2.0.0

I will update the requirements.txt for Flask-User v0.6.7.

**Comment by Shizmob** [comment]
Thank you!

**Comment by scheung38** [comment]
Still seeing this:
```
python manage.py init_db
/home/osboxes/anaconda/envs/py27/lib/python2.7/site-packages/passlib/handlers/bcrypt.py:320: UserWarning: passlib.hash.bcrypt: Your installation of the 'pybcrypt' backend is vulnerable to the bsd wraparound bug, and should be upgraded or replaced with another backend (this warning will be fatal under passlib 1.7)
  "(this warning will be fatal under passlib 1.7)" % backend)
```
so do I need to install pybcrypt?

**Comment by Xender** [comment]
@scheung38 - You need to **un**install `pybrypt` and install `bcrypt` pip packages.

**Comment by scheung38** [comment]
If I uninstall pybrypt as you pointed out then:
```
File "/home/osboxes/anaconda/envs/py27/lib/python2.7/site-packages/passlib/utils/handlers.py", line 1442, in set_backend
    raise exc.MissingBackendError(cls._no_backends_msg())
MissingBackendError: no bcrypt backends available -- recommend you install one (e.g. 'pip install bcrypt')
```

**Comment by Xender** [comment]
Maybe try reinstalling and/or upgrading passlib and/or bcrypt?

I don't really have a clue beside "it shouldn't really happen", so I have only such a generic advice (something similar (empty bcrypt module with no content at all) happened to me and reinstall helped, though).

**Comment by scheung38** [comment]
Thanks @Xender did you face similar issue of not able to register a new user? and did you successfully manage to do so after the above advice?

**Comment by Xender** [comment]
I did have issue with `bcrypt` being installed as empty module and yes, reinstall worked.

Also, if generic "upgrade/reinstall" doesn't help, it doesn't look like a bug in `Flask-User`, more like in `Passlib`, `bcrypt` or `pip` (or whatever Python package manager you're using).

**Comment by scheung38** [comment]
Is Flask-User stable enough at the moment for usage?

**Comment by Xender** [comment]
@scheung38 - I have no idea and I'd also like to know that, but that `bcrypt` issue doesn't really have to do with `Flask-User` in any way beside having `passlib` as a dependency.
